const themes = {
    colors: {
        brand: {
            primary: {
                lightest: "#F29A99",
                light: "#F58080",
                medium: "#ef5350",
                dark: "#A32826",
                darkest: "#702625",
            },
            secondary: {
                lightest: "#F0EF67",
                light: "#fdc91b",
                medium: "#fdc91b",
                dark: "#fdc91b",
                darkest: "#fdc91b",
            },
        },
        feedback: {
            success: {
                lightest: "#4FF082",
                medium: "#4FF082",
                darkest: "#15A342",
            },
            error: {
                lightest: "#8A0000",
                medium: "#F01C18",
                darkest: "#A30300",
            },
            warning: {
                lightest: "#704D00",
                medium: "#F5BC00",
                darkest: "#FFE285",
            },
            info: {
                lightest: "#37A3F0",
                medium: "#37A3F0",
                darkest: "#2E72A3",
            },
        },
        support: {},
        tints: {},
        grayscale: {
            white: "#fff",
            lightest: "#ECECEC",
            light: "#C8C8C8",
            medium: "#747474",
            dark: "#555555",
            darkest: "#212121",
            black: "#000",
        },
    },
    fonts: {
        family: {
            base: "Roboto, sans-serif",
            highlight: "Righteous, cursive",
        },
        size: {
            _4XS: "0.5rem",
            _3XS: "0.6rem",
            _2XS: "0.8rem",
            XS: "1rem",
            SM: "1.2rem",
            MD: "1.4rem",
            LG: "1.6rem",
            XL: "2rem",
            _2XL: "2.4rem",
            _3LG: "3.2rem",
            _4XL: "4.2rem",
            _5XL: "5.2rem",
        },
        weight: {
            light: "300",
            regular: "400",
            medium: "500",
            bold: "700",
            extraBold: "800",
        },
        height: {
            SM: "1",
            MD: "1.3",
            LG: "1.5",
        },
    },
    borderRadius: {
        SM: "8px",
        MD: "16px",
        LG: "24px",
        circle: "50%",
        pill: "500px",
    },
    borderWidth: {
        XS: "1px",
        SM: "2px",
        MD: "4px",
        LG: "8px",
    },
    shadows: {
        level1: "0px 4px 16px rgba(0, 0, 0, 0.08)",
        level2: "0px 8px 24px rgba(0, 0, 0, 0.08)",
        level3: "0px 16px 32px rgba(0, 0, 0, 0.08)",
        level4: "0px 16px 48px rgba(0, 0, 0, 0.08)",
    },
    spacing: {
        none: "0",
        _3XS: "0.25rem",
        _2XS: "0.5rem",
        XS: "1rem",
        SM: "1.5rem",
        MD: "2rem",
        LG: "2.5rem",
        XL: "3rem",
        _2XL: "3.5rem",
        _3XL: "4rem",
    },
    opacities: {
        semiOpaque: "0.8",
        intense: "0.64",
        medium: "0.32",
        weak: "0.24",
        light: "0.16",
        semiTransparent: "0.08",
        transparent: "0",
    },
};

export const newTheme = {
    colors: {
        brand: {
            primary: {
                lightest: "#FFBACB",
                light: "#F299AF",
                medium: "#F01C18",
                dark: "#A32826",
                darkest: "#702625",
            },
            secondary: {
                lightest: "#F0EF67",
                light: "#fdc91b",
                medium: "#fdc91b",
                dark: "#fdc91b",
                darkest: "#115eca",
            },
        },
        feedback: {
            success: {
                lightest: "#4FF082",
                medium: "#4FF082",
                darkest: "#15A342",
            },
            error: {
                lightest: "#8A0000",
                medium: "#555555",
                darkest: "#A30300",
            },
            warning: {
                lightest: "#704D00",
                medium: "#F5BC00",
                darkest: "#FFE285",
            },
            info: {
                lightest: "#37A3F0",
                medium: "#37A3F0",
                darkest: "#2E72A3",
            },
        },
        support: {},
        tints: {},
        grayscale: {
            white: "#fff",
            lightest: "#ECECEC",
            light: "#C8C8C8",
            medium: "#A6586B",
            dark: "#555555",
            darkest: "#212121",
            black: "#000",
        },
        pokemonTypes: {
            normal: "#a4acaf",
            fire: "#fd7d24",
            water: "#4592c4",
            electric: "#eed535",
            grass: "#9bcc50",
            ice: "#51c4e7",
            fighting: "#d56723",
            poison: "#b97fc9",
            ground: "linear-gradient(to bottom, #f7de3f, #ab9842)",
            flying: "linear-gradient(to bottom, #3dc7ef, #bdb9b8)",
            psychic: "#f366b9",
            bug: "#729f3f",
            rock: "#a38c21",
            ghost: "#7b62a3",
            dragon: "linear-gradient(to bottom, #53a4cf, #f16e57)",
            dark: "#707070",
            steel: "#9eb7b8",
            fairy: "#fdb9e9",
        },
    },
    fonts: {
        family: {
            base: "Roboto, sans-serif",
            highlight: "Righteous, cursive",
        },
        size: {
            _4XS: "0.5rem",
            _3XS: "0.6rem",
            _2XS: "0.8rem",
            XS: "1rem",
            SM: "1.2rem",
            MD: "1.4rem",
            LG: "1.6rem",
            XL: "2rem",
            _2XL: "2.4rem",
            _3XL: "3rem",
            _4XL: "4.2rem",
            _5XL: "6rem",
        },
        weight: {
            light: "300",
            regular: "400",
            medium: "500",
            bold: "700",
            extraBold: "800",
        },
        height: {
            SM: "1",
            MD: "1.3",
            LG: "1.5",
        },
    },
    borderRadius: {
        SM: "8px",
        MD: "16px",
        LG: "24px",
        circle: "50%",
        pill: "500px",
    },
    borderWidth: {
        XS: "1px",
        SM: "2px",
        MD: "4px",
        LG: "8px",
    },
    shadows: {
        level1: "0px 4px 16px rgba(0, 0, 0, 0.08)",
        level2: "0px 8px 24px rgba(0, 0, 0, 0.08)",
        level3: "0px 16px 32px rgba(0, 0, 0, 0.08)",
        level4: "0px 16px 48px rgba(0, 0, 0, 0.08)",
    },
    spacing: {
        none: "0",
        _3XS: "0.25rem",
        _2XS: "0.5rem",
        XS: "1rem",
        SM: "1.5rem",
        MD: "2rem",
        LG: "2.5rem",
        XL: "3rem",
        _2XL: "3.5rem",
        _3XL: "4rem",
    },
    opacities: {
        semiOpaque: "0.8",
        intense: "0.64",
        medium: "0.32",
        weak: "0.24",
        light: "0.16",
        semiTransparent: "0.08",
        transparent: "0",
    },
};

export default themes;
